spring:
  application:
    name: xiaoshou
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost/xiaoshou?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: xiaoshou
    password: xiaoshou
  jackson:
    default-property-inclusion: NON_NULL
  mvc:
    servlet:
      path: /api
    static-path-pattern: /**

# server:
#   error:
#     whitelabel:
#       enabled: false

logging:
  level:
    com.gxwsxx: DEBUG
#    org.mybatis.spring: DEBUG

mybatis:
#  mapper-locations: classpath:mapper/*.xml
  configuration:
    lazy-loading-enabled: true
    default-statement-timeout: 30
    map-underscore-to-camel-case: true

